# Generated by Django 4.0.4 on 2022-04-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='jabatan',
            field=models.CharField(default='a', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='nama',
            field=models.CharField(max_length=256),
        ),
    ]
