# Generated by Django 4.0.4 on 2022-04-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pegawai_jabatan_alter_pegawai_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pegawai',
            field=models.BooleanField(default=True, verbose_name='status pegawai'),
        ),
    ]
