# Generated by Django 4.0.4 on 2022-04-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_is_pegawai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_pegawai',
            field=models.BooleanField(default=False, verbose_name='status pegawai'),
        ),
    ]
